spring:
  datasource:
    url: jdbc:mysql://localhost/Unicorn?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

springdoc:
  api-docs.path: /api-docs